/**
 * Generates parameter ID definitions for the C++ and web layers from a plugin's
 * parameter JSON files, keeping `parameters.*.json` the single source of truth.
 * The Rust side is generated separately by the plugin's `lib/dsp/build.rs` from
 * the same JSON, in the same order, so indices always agree.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

import type { ParamDef, ParamsFile, PluginType } from './types'

const GENERATED_NOTICE = '// Generated by @bbx-audio/plugin -- DO NOT EDIT.'

const RELAY_TYPES: Record<string, [string, string]> = {
    float: ['juce::WebSliderRelay', 'juce::WebSliderParameterAttachment'],
    choice: ['juce::WebComboBoxRelay', 'juce::WebComboBoxParameterAttachment'],
    boolean: ['juce::WebToggleButtonRelay', 'juce::WebToggleButtonParameterAttachment'],
}

/**
 * Walks up from `from` to the nearest directory containing a `plugin.env`,
 * i.e. the root of a plugin repo derived from `blackboxaudio/template-plugin`.
 */
export function findPluginRoot(from: string): string {
    let dir = resolve(from)
    for (;;) {
        if (existsSync(join(dir, 'plugin.env'))) {
            return dir
        }
        const parent = dirname(dir)
        if (parent === dir) {
            throw new Error(
                `No plugin.env found from ${resolve(from)} upward — ` +
                    'not inside a plugin repo derived from blackboxaudio/template-plugin'
            )
        }
        dir = parent
    }
}

function readPluginType(repoRoot: string): PluginType {
    const env = readFileSync(join(repoRoot, 'plugin.env'), 'utf8')
    const match = env.match(/^PLUGIN_TYPE=(\w+)/m)
    if (!match) throw new Error('PLUGIN_TYPE not found in plugin.env')
    const pluginType = match[1]
    if (pluginType !== 'effect' && pluginType !== 'synth') {
        throw new Error(`Invalid PLUGIN_TYPE "${pluginType}" in plugin.env (expected effect | synth)`)
    }
    return pluginType
}

function readParameters(repoRoot: string, pluginType: PluginType): ParamDef[] {
    const file = join(repoRoot, `parameters.${pluginType}.json`)
    return (JSON.parse(readFileSync(file, 'utf8')) as ParamsFile).parameters
}

function readParametersIfPresent(repoRoot: string, pluginType: PluginType): ParamDef[] {
    const file = join(repoRoot, `parameters.${pluginType}.json`)
    if (!existsSync(file)) return []
    return (JSON.parse(readFileSync(file, 'utf8')) as ParamsFile).parameters
}

function toPascalCase(id: string): string {
    return id
        .split('_')
        .map((part) => part.charAt(0) + part.slice(1).toLowerCase())
        .join('')
}

function toCamelCase(id: string): string {
    const pascal = toPascalCase(id)
    return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

export function generateCppHeader(parameters: ParamDef[]): string {
    const ids = parameters.map((p) => `    inline const juce::String ${p.id}_PARAM_ID = "${p.id}";`).join('\n')

    const relayEntries = parameters
        .map((p) => {
            const relay = RELAY_TYPES[p.type]
            if (!relay) {
                throw new Error(`Unknown parameter type "${p.type}" for "${p.id}" (expected float | choice | boolean)`)
            }
            const [relayType, attachmentType] = relay
            return `    X(${toCamelCase(p.id)}, ${p.id}_PARAM_ID, ${relayType}, ${attachmentType})`
        })
        .join(' \\\n')

    return `#pragma once

${GENERATED_NOTICE}

#include <juce_core/juce_core.h>

namespace parameters {
${ids}
}

// clang-format off
#define BBX_FOR_EACH_PARAM_RELAY(X) \\
${relayEntries}
// clang-format on
`
}

export function generateTsModule(
    effectParameters: ParamDef[],
    synthParameters: ParamDef[],
    pluginType: PluginType
): string {
    const seen = new Set<string>()
    const entries: string[] = []
    for (const [section, parameters] of [
        ['Effect parameters', effectParameters],
        ['Synth parameters', synthParameters],
    ] as const) {
        entries.push(`    // ${section}`)
        for (const p of parameters) {
            if (seen.has(p.id)) continue
            seen.add(p.id)
            entries.push(`    ${toPascalCase(p.id)} = '${p.id}',`)
        }
    }

    return `${GENERATED_NOTICE}

export enum ParameterId {
${entries.join('\n')}
}

export const pluginType: 'synth' | 'effect' = '${pluginType}'
`
}

export interface GenerateParamsOptions {
    /** Plugin repo root; defaults to walking up from the current working directory. */
    repoRoot?: string
    /** Emit `bbx_generated_params.h` into this directory. */
    cppOutDir?: string | null
    /** Emit the web `ParameterId` module. */
    web?: boolean
    /** Web module output path; defaults to `<repoRoot>/web/src/lib/generated/params.ts`. */
    webOutFile?: string
}

export function generateParams(options: GenerateParamsOptions = {}): PluginType {
    const repoRoot = options.repoRoot ?? findPluginRoot(process.cwd())
    const { cppOutDir = null, web = false } = options
    const pluginType = readPluginType(repoRoot)

    if (cppOutDir) {
        const parameters = readParameters(repoRoot, pluginType)
        mkdirSync(cppOutDir, { recursive: true })
        writeFileSync(join(cppOutDir, 'bbx_generated_params.h'), generateCppHeader(parameters))
    }

    if (web) {
        const outFile = options.webOutFile ?? join(repoRoot, 'web', 'src', 'lib', 'generated', 'params.ts')
        mkdirSync(dirname(outFile), { recursive: true })
        // The active plugin type's file must exist (it defines the plugin), but the
        // counterpart may be deleted by plugins that are only ever one type.
        const effectParameters =
            pluginType === 'effect' ? readParameters(repoRoot, 'effect') : readParametersIfPresent(repoRoot, 'effect')
        const synthParameters =
            pluginType === 'synth' ? readParameters(repoRoot, 'synth') : readParametersIfPresent(repoRoot, 'synth')
        writeFileSync(outFile, generateTsModule(effectParameters, synthParameters, pluginType))
    }

    return pluginType
}
