/* BBX DSP - Auto-generated C bindings
 *
 * This header provides C-compatible bindings for the bbx_dsp Rust library.
 * Use with JUCE audio plugins for full Rust DSP integration.
 *
 * DO NOT EDIT - This file is auto-generated by cbindgen.
 */

#ifndef BBX_DSP_H
#define BBX_DSP_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Default buffer size for DSP `Graph`s.
 */
#define DEFAULT_BUFFER_SIZE 512

/*
 Default sample rate for DSP `Graph`s.
 */
#define DEFAULT_SAMPLE_RATE 44100.0

/*
 Opaque DSP engine type for C/C++ interop.

 This wraps a `Graph<f32>` and provides a stable ABI for FFI.
 */
typedef struct DspEngine DspEngine;

/*
 Atomic f32 wrapper using bit-casting through u32.

 This matches the memory layout of `std::atomic<float>` in C++
 and allows lock-free parameter updates from the UI thread.
 */
typedef struct AtomicF32 {
    AtomicU32 _0;
} AtomicF32;

/*
 Create a new DSP engine with default configuration.

 # Arguments
 * `sample_rate` - Audio sample rate in Hz (e.g., 44100.0, 48000.0)
 * `buffer_size` - Number of samples per processing block
 * `num_channels` - Number of audio channels (typically 2 for stereo)

 # Returns
 Pointer to the new engine, or null on failure.

 # Safety
 The returned pointer must be freed with `bbx_destroy_engine`.
 */

struct DspEngine *bbx_create_engine(double sample_rate,
                                    uintptr_t buffer_size,
                                    uintptr_t num_channels)
;

/*
 Create a DSP engine from a JSON configuration string.

 # Arguments
 * `config_str` - Pointer to JSON configuration string
 * `config_len` - Length of the configuration string in bytes
 * `sample_rate` - Audio sample rate in Hz
 * `buffer_size` - Number of samples per processing block
 * `num_channels` - Number of audio channels

 # Returns
 Pointer to the new engine, or null on parse/creation failure.

 # Safety
 The config_str pointer must be valid for config_len bytes.
 The returned pointer must be freed with `bbx_destroy_engine`.
 */

struct DspEngine *bbx_create_engine_from_config_str(const char *config_str,
                                                    uintptr_t config_len,
                                                    double sample_rate,
                                                    uintptr_t buffer_size,
                                                    uintptr_t num_channels)
;

/*
 Destroy a DSP engine and free its resources.

 # Arguments
 * `engine` - Pointer to the engine to destroy (can be null)

 # Safety
 The engine pointer must have been created by `bbx_create_engine` or
 `bbx_create_engine_from_config_str`, or be null.
 */
 void bbx_destroy_engine(struct DspEngine *engine) ;

/*
 Prepare the DSP engine for playback.

 Call this from JUCE's `prepareToPlay` method whenever the sample rate
 or buffer size changes.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `sample_rate` - New sample rate in Hz
 * `buffer_size` - New buffer size in samples

 # Safety
 The engine pointer must be valid.
 */
 void bbx_prepare(struct DspEngine *engine, double _sample_rate, uintptr_t _buffer_size) ;

/*
 Reset all DSP state (clear filters, reset phases, etc.).

 Call this when playback stops or the plugin is bypassed.

 # Arguments
 * `engine` - Pointer to the DSP engine

 # Safety
 The engine pointer must be valid.
 */
 void bbx_reset(struct DspEngine *engine) ;

/*
 Process stereo audio through the DSP engine.

 Supports in-place processing (input and output can point to the same buffer).

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `input_left` - Pointer to left channel input samples
 * `input_right` - Pointer to right channel input samples
 * `output_left` - Pointer to left channel output samples
 * `output_right` - Pointer to right channel output samples
 * `num_samples` - Number of samples to process

 # Safety
 All buffer pointers must be valid for num_samples elements.
 The engine pointer must be valid.
 */

void bbx_process(struct DspEngine *engine,
                 const float *input_left,
                 const float *input_right,
                 float *output_left,
                 float *output_right,
                 uintptr_t num_samples)
;

/*
 Process multi-channel audio through the DSP engine.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `inputs` - Array of pointers to input channel buffers
 * `outputs` - Array of pointers to output channel buffers
 * `num_channels` - Number of channels
 * `num_samples` - Number of samples per channel

 # Safety
 All buffer pointers must be valid. The engine pointer must be valid.
 */

void bbx_process_multi(struct DspEngine *engine,
                       const float *const *inputs,
                       float **outputs,
                       uintptr_t num_channels,
                       uintptr_t num_samples)
;

/*
 Set a parameter value directly.

 Use this for non-automatable parameters or one-time configuration.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `block_id` - ID of the block containing the parameter
 * `param_name` - Null-terminated C string with the parameter name
 * `value` - New parameter value

 # Safety
 The engine pointer and param_name must be valid.
 */

void bbx_set_parameter(struct DspEngine *engine,
                       uintptr_t block_id,
                       const char *param_name,
                       float value)
;

/*
 Bind a parameter to an external atomic source (JUCE AudioProcessorValueTreeState).

 Once bound, the Rust DSP will read parameter values directly from the
 atomic pointer on each process call, enabling lock-free automation.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `block_id` - ID of the block containing the parameter
 * `param_name` - Null-terminated C string with the parameter name
 * `atomic_ptr` - Pointer to the external atomic (std::atomic<float>* from JUCE)

 # Safety
 The engine pointer, param_name, and atomic_ptr must be valid.
 The atomic_ptr must remain valid for the lifetime of the binding.
 */

void bbx_bind_parameter(struct DspEngine *engine,
                        uintptr_t block_id,
                        const char *param_name,
                        const struct AtomicF32 *atomic_ptr)
;

/*
 Unbind a parameter from its external source.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `block_id` - ID of the block containing the parameter
 * `param_name` - Null-terminated C string with the parameter name

 # Safety
 The engine pointer and param_name must be valid.
 */
 void bbx_unbind_parameter(struct DspEngine *engine, uintptr_t block_id, const char *param_name) ;

/*
 Get the current value of a parameter.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `block_id` - ID of the block containing the parameter
 * `param_name` - Null-terminated C string with the parameter name

 # Returns
 The current parameter value, or 0.0 on error.

 # Safety
 The engine pointer and param_name must be valid.
 */
 float bbx_get_parameter(struct DspEngine *engine, uintptr_t block_id, const char *param_name) ;

/*
 Add a block to the graph.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `block_type` - Null-terminated C string with the block type
                  ("oscillator", "gain", "filter", "lfo", etc.)
 * `config_json` - Null-terminated JSON string with block-specific configuration

 # Returns
 The block ID on success, or -1 on error.

 # Safety
 The engine pointer, block_type, and config_json must be valid.
 */
 int32_t bbx_add_block(struct DspEngine *engine, const char *block_type, const char *config_json) ;

/*
 Connect two blocks in the graph.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `source_block` - ID of the source block
 * `source_output` - Output index on the source block
 * `dest_block` - ID of the destination block
 * `dest_input` - Input index on the destination block

 # Returns
 true on success, false on error.

 # Safety
 The engine pointer must be valid.
 */

bool bbx_connect(struct DspEngine *engine,
                 uintptr_t source_block,
                 uintptr_t source_output,
                 uintptr_t dest_block,
                 uintptr_t dest_input)
;

/*
 Rebuild the execution order after graph changes.

 Must be called after adding/removing blocks or connections.

 # Arguments
 * `engine` - Pointer to the DSP engine

 # Safety
 The engine pointer must be valid.
 */
 void bbx_rebuild_graph(struct DspEngine *engine) ;

/*
 Add a modulation connection between a modulator and a parameter.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `modulator_block` - ID of the modulator block (e.g., LFO)
 * `target_block` - ID of the block containing the target parameter
 * `param_name` - Null-terminated C string with the parameter name
 * `depth` - Modulation depth (-1.0 to 1.0)

 # Returns
 true on success, false on error (e.g., all modulation slots full).

 # Safety
 The engine pointer and param_name must be valid.
 */

bool bbx_add_modulation(struct DspEngine *engine,
                        uintptr_t modulator_block,
                        uintptr_t target_block,
                        const char *param_name,
                        float depth)
;

/*
 Remove a modulation connection.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `modulator_block` - ID of the modulator block
 * `target_block` - ID of the block containing the target parameter
 * `param_name` - Null-terminated C string with the parameter name

 # Returns
 true on success, false on error.

 # Safety
 The engine pointer and param_name must be valid.
 */

bool bbx_remove_modulation(struct DspEngine *engine,
                           uintptr_t modulator_block,
                           uintptr_t target_block,
                           const char *param_name)
;

/*
 Set the depth of an existing modulation connection.

 # Arguments
 * `engine` - Pointer to the DSP engine
 * `modulator_block` - ID of the modulator block
 * `target_block` - ID of the block containing the target parameter
 * `param_name` - Null-terminated C string with the parameter name
 * `depth` - New modulation depth (-1.0 to 1.0)

 # Safety
 The engine pointer and param_name must be valid.
 */

void bbx_set_modulation_depth(struct DspEngine *engine,
                              uintptr_t modulator_block,
                              uintptr_t target_block,
                              const char *param_name,
                              float depth)
;

/*
 Get the library version string.

 # Returns
 A null-terminated C string with the version (e.g., "0.1.0").
 The returned pointer is static and should not be freed.
 */
 const char *bbx_version(void) ;

#endif  /* BBX_DSP_H */
