name: Clippy

on:
    pull_request:
    push:
        branches:
            - developer
            - main

jobs:
    test:
        name: Cargo Clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: nightly
                  override: true

            - name: Run Clippy
              run: cargo +nightly clippy